export const GET_FETCH_TOTAL_SCORE = 'GET_FETCH_TOTAL_SCORE';
export const SET_FETCH_TOTAL_SCORE = 'SET_FETCH_TOTAL_SCORE';



export const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR';
export const SET_NOTIFICATION_LOADING = 'SET_NOTIFICATION_LOADING';

